### ISSUE TITLE
Does this need Bonus Chest turned on?

### ISSUE THREAD

**Issue by Traehgniw** [Komaru-cats/Various-Starting-Loot#1]
Does this need Bonus Chest turned on to generate the starting loot? I have made a few worlds and couldn't find any starting loot chests, but they might have been buried in the ground or something

**Comment by ItzSkyReed** [comment]
It is not necessary to include the starting loot, since it is impossible to change it in this way with the help of a datapack. As for your problem, you may not have initialized the datapack if you used it, and not the version with the mod.

**Comment by ItzSkyReed** [comment]
No it does.
