### ISSUE TITLE
Is 1.18.2 backport possible?

### ISSUE THREAD

**Issue by vadim-a-yegorov** [Komaru-cats/Various-Starting-Loot#2]

**Comment by ItzSkyReed** [comment]
Check, maybe it works on 1.18.2, if not, I'll see what's the matter

**Comment by vadim-a-yegorov** [comment]
> Check, maybe it works on 1.18.2, if not, I'll see what's the matter

Tested. Not working on 1.18.2 Fabric.

**Comment by vadim-a-yegorov** [comment]
Sorry I get it wrong, I thought it's a starter kit that players receive on spawn…
