### ISSUE TITLE
Does it support Terralith biomes?

### ISSUE THREAD

**Issue by vadim-a-yegorov** [Komaru-cats/Various-Starting-Loot#3]
Does it support Terralith biomes? If not, I'll try to fix it by the nearest time.

**Comment by ItzSkyReed** [comment]
not yet

**Comment by vadim-a-yegorov** [comment]
> not yet

The "Close" button should be used to close an issue as complete or irrelevant. I see you closed it for no reason, you probably did it unintentionally. Please reopen. I will add Terralith and Tectonic biomes later.

**Comment by ItzSkyReed** [comment]
Sorry, but I have no desire to update this datapack.

**Comment by vadim-a-yegorov** [comment]
I’m sorry I didn’t fix it because I abandoned my latest project that required your mod.
Sooner or later I might get back to it.

**Comment by ItzSkyReed** [comment]
I am very sorry for not doing anything for so long, I haven't got motivation, but now I have it and I am actively engaged in developing this datapack. I will add support for new biomes soon, first for terralith, then I plan to add support for Terrestria
