### ISSUE TITLE
[FEATURE REQUEST] I'm looking for solution that will give all players starting loot on spawn, not as a chest

### ISSUE THREAD

**Issue by vadim-a-yegorov** [Komaru-cats/Various-Starting-Loot#4]
I thought this datapack works as a starting kit but it's not xD We can work on that together. Keep on touch.

**Comment by ItzSkyReed** [comment]
Можем продолжить на русском, если так будет удобнее? В целом, это не сложно будет сделать, только надо посмотреть на сколько сильно это в теории может снижать производительность. Я займусь этим чуть позже

**Comment by ItzSkyReed** [comment]
Sorry, but I have no desire to update this datapack.

**Comment by ItzSkyReed** [comment]
Completed. @vadim-a-yegorov

**Comment by vadim-a-yegorov** [comment]
Wow! Thanks!
