### ISSUE TITLE
[Suggestion] Generate different chest variants for different biota!

### ISSUE THREAD

**Issue by Qee1y** [Komaru-cats/Various-Starting-Loot#5]

**Comment by ItzSkyReed** [comment]
Hm, sounds interesting, if I understand you correctly. I will think about it and how can I do this in unique way

**Comment by Qee1y** [comment]
> 嗯，听起来很有趣，如果我理解正确的话。我会考虑它，我如何以独特的方式做到这一点
翻译还是多少有问题， 主要是针对不同群系，生成该群系的奖励箱的风格。

**Comment by Qee1y** [comment]
> Hm, sounds interesting, if I understand you correctly. I will think about it and how can I do this in unique way

The different biome bonus boxes are generated primarily for different biomes in much the same style as the biome loot tables you make. You might consider using other mods with different texture variants of chests, such as "quark" with different textures.

I apologize for using a translator, it may not be an accurate description ....

**Comment by ItzSkyReed** [comment]
My project is a datapack so I can't detect that player has or hasn't got mods so this is not possible.

**Comment by Qee1y** [comment]
> My project is a datapack so I can't detect that player has or hasn't got mods so this is not possible.


I think it only needs to be linkage, so that players can add according to their needs, even without mods, it can run normally.
