### ISSUE TITLE
Issue: creates a new loot barrel even when bonus chest is disabled (mod)

### ISSUE THREAD

**Issue by steve-the-player** [Komaru-cats/Various-Starting-Loot#6]
Running this as a mod, I've noticed that when running worldgen you still have the options for a bonus chest toggle, but this will completely ignore that and give you a barrel. If bonus chest is enabled, the standard bonus chest will appear a few blocks away surrounded by the usual torches, in addition to the barrel that spawns directly in front of you. When running this as a mod, it would be nice to have the option to disable, enable as it currently is, or enable and replace the vanilla bonus chest, but I realize that as a datapack this is harder to implement. It would also be nice to have a setting whether or not it ignores the bonus chest y/n option in worldgen.

**Comment by ItzSkyReed** [comment]
Despite the fact that this is a mod, it is essentially a datapack wrapped in a mod in order not to insert it into a new world every time, so I do not have the technical capabilities to interact with minecraft like this. I want to make this project as a normal mod in the future, but unfortunately, I don't have enough time at the moment.
