### ISSUE TITLE
Issue (as mod): Generates new bonus barrel upon every relog

### ISSUE THREAD

**Issue by steve-the-player** [Komaru-cats/Various-Starting-Loot#7]
Haven't tested this running it as a datapack, but when running it as a mod it spawns a barrel every time you relog.

**Comment by ItzSkyReed** [comment]
What version of various starting loot are you using?

**Comment by steve-the-player** [comment]
I think it was the most recent version, just packaged as a mod rather than a datapack. 2.0+mod

**Comment by ItzSkyReed** [comment]
Fixed
